# Generated by Django 3.2.7 on 2022-04-18 13:10

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='客户姓名')),
                ('telephone', models.CharField(max_length=200, null=True, verbose_name='电话')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='收货地址')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='收卡时间')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='品牌')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='型号')),
                ('sn_num', models.CharField(max_length=200, null=True, verbose_name='SN码')),
                ('new', models.CharField(choices=[('NEW', '首次维修'), ('TH', '二修')], default='NEW', max_length=20, verbose_name='首修or二修')),
                ('before_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='order/', verbose_name='维修前图片')),
                ('repaired_pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='order/', verbose_name='维修后图片')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
