# Generated by Django 3.2.7 on 2022-04-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_the_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new',
        ),
        migrations.RemoveField(
            model_name='order',
            name='the_id',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, '已接单'), (2, '已清洗'), (3, '已维修'), (4, '已完成')], default=0, max_length=20, verbose_name='订单状态'),
        ),
    ]
