# Generated by Django 3.2.7 on 2022-04-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220423_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, '已接单'), (1, '已清洗'), (2, '已维修'), (3, '已完成')], default=0, max_length=20, verbose_name='订单状态'),
        ),
    ]
