# Generated by Django 3.2.7 on 2022-04-23 02:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='before_pic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='repaired_pic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sn_num',
        ),
        migrations.AddField(
            model_name='order',
            name='before_pic_back',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='order/', verbose_name='维修前图片反面'),
        ),
        migrations.AddField(
            model_name='order',
            name='before_pic_front',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='order/', verbose_name='维修前图片正面'),
        ),
        migrations.AddField(
            model_name='order',
            name='repaired_pic_back',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='repaired/', verbose_name='维修后图片反面'),
        ),
        migrations.AddField(
            model_name='order',
            name='repaired_pic_front',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='repaired/', verbose_name='维修后图片正面'),
        ),
        migrations.AddField(
            model_name='order',
            name='sn_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='SN/', verbose_name='SN码照片'),
        ),
    ]
