# Generated by Django 3.2.7 on 2022-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220423_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('正在清洗中..', '已接单'), ('已清洗，正在修复中..', '已清洗'), ('repaired', '已维修'), ('finish', '已完成')], default='have order', max_length=20, verbose_name='订单状态'),
        ),
    ]
