# Generated by Django 3.2.7 on 2022-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220425_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('正在清洗中..', '已接单'), ('已清洗，正在修复中..', '已清洗'), ('已修复，正在检测中..', '已维修'), ('各项检测正常，已发回', '已完成')], default='have order', max_length=20, verbose_name='订单状态'),
        ),
    ]
